# Generated by Django 5.2.15 on 2026-06-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bedspace",
            name="notice_given",
            field=models.BooleanField(default=False),
        ),
    ]
