# Generated by Django 5.2.15 on 2026-08-02 08:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_bedspace_notice_given'),
        ('tenants', '0002_alter_tenantprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_utility_cap_per_tenant', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=6)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('units_used', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='properties.block')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reading_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_share', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tenant_excess', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_paid', models.BooleanField(default=False)),
                ('meter_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='utilities.meterreading')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_bills', to='tenants.tenantprofile')),
            ],
            options={
                'ordering': ['-meter_reading__reading_date'],
                'unique_together': {('meter_reading', 'tenant')},
            },
        ),
    ]
